### ISSUE TITLE
Improve example site

### ISSUE THREAD

**Issue by PhiLhoSoft** [akashacms/akashacms-example#1]
The example site (the online one or the one installed by build) isn't very nice...
I understand you want to keep it simple, so it is mostly OK.
But the header has a div with the Bootstrap's `row` class, which has a negative margin left (and right): on Firefox and Chrome for Windows, I see only "ashaCMS" for the first link.
I suggest to replace this class with `nav`, for example, and it would use some (positive) left margin, too.

Moreover, the Markdown page still tell you use Remarkable as engine, but you switched to Markdown-it...

Might be interesting to change the links like http://akashacms.com/plugins/booknav.html to be clickable, too...

**Comment by robogeek** [comment]
Fixed

**Comment by PhiLhoSoft** [comment]
Much better!
Minor last remark: perhaps you want to set a title on [the video page](http://example.akashacms.com/video.html).
